SELECT
    DATE_DAY AS DATE,
    EXTRACT(YEAR FROM DATE_DAY) AS YEAR,
    EXTRACT(MONTH FROM DATE_DAY) AS MONTH,
    MONTHNAME(DATE_DAY) AS MONTH_NAME,
    EXTRACT(QUARTER FROM DATE_DAY) AS QUARTER,
    EXTRACT(DAYOFWEEK FROM DATE_DAY) AS DAY_OF_WEEK,
    CASE WHEN DAYOFWEEK(DATE_DAY) IN (0, 6) THEN TRUE ELSE FALSE END AS IS_WEEKEND
FROM (
    -- This generates a range of dates
    SELECT 
        DATEADD(DAY, SEQ4(), '2025-01-01') AS DATE_DAY
    FROM TABLE(GENERATOR(ROWCOUNT => 730)) -- Covers 2 years
)