WITH daily_ads AS (
    
    SELECT 
        DATE,
        CAMPAIGN_ID,
        PLATFORM,
        SUM(SPEND) AS TOTAL_SPEND,
        SUM(CLICKS) AS TOTAL_CLICKS
    FROM {{ ref('silver_ad_spend') }}
    GROUP BY 1, 2, 3
),

daily_revenue AS (

    SELECT 
        DATE AS DATE,
        CAMPAIGN_ID,
        PLATFORM,
        SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
        COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
    FROM {{ ref('order_attribution') }}
    GROUP BY 1, 2, 3
)

SELECT
    
    COALESCE(a.DATE, r.DATE) AS DATE,
    LOWER(COALESCE(a.PLATFORM, r.PLATFORM)) AS PLATFORM,
    COALESCE(a.CAMPAIGN_ID, r.CAMPAIGN_ID) AS CAMPAIGN_ID,
    
   
    COALESCE(a.TOTAL_SPEND, 0) AS SPEND,
    COALESCE(a.TOTAL_CLICKS, 0) AS CLICKS,
    ROUND(COALESCE(r.TOTAL_REVENUE, 0)) AS REVENUE,
    COALESCE(r.TOTAL_ORDERS, 0) AS ORDERS,
    

    COALESCE(ROUND(r.TOTAL_REVENUE / NULLIF(a.TOTAL_SPEND, 0), 2), 0) AS ROAS,
    COALESCE(ROUND(a.TOTAL_SPEND / NULLIF(r.TOTAL_ORDERS, 0), 2), 0) AS CPA,
    
    
    COALESCE(ROUND(CAST(r.TOTAL_ORDERS AS FLOAT) / NULLIF(a.TOTAL_CLICKS, 0), 4), 0) AS CONVERSION_RATE

FROM daily_ads a
FULL OUTER JOIN daily_revenue r 
    ON a.DATE = r.DATE 
    AND a.CAMPAIGN_ID = r.CAMPAIGN_ID
    AND a.PLATFORM = r.PLATFORM